// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpH63O9ktSUDqKMvYVv_AYcrVsqs9IaB0',
    appId: '1:26995370245:web:44978745974a17a1076f6c',
    messagingSenderId: '26995370245',
    projectId: 'fitness-mobile-ef3ca',
    authDomain: 'fitness-mobile-ef3ca.firebaseapp.com',
    storageBucket: 'fitness-mobile-ef3ca.firebasestorage.app',
    measurementId: 'G-168Y29T2W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLdIIHi60sODhN8nB1N1UMx0NviXknuz4',
    appId: '1:26995370245:android:6a95549256ecc25e076f6c',
    messagingSenderId: '26995370245',
    projectId: 'fitness-mobile-ef3ca',
    storageBucket: 'fitness-mobile-ef3ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpdqxEGG76BO_ZvamDW886TnXTzZ39Jts',
    appId: '1:26995370245:ios:362285a67b72c67f076f6c',
    messagingSenderId: '26995370245',
    projectId: 'fitness-mobile-ef3ca',
    storageBucket: 'fitness-mobile-ef3ca.firebasestorage.app',
    androidClientId: '26995370245-0hbspa2s2on5b7fur5scitq2fn0tatb8.apps.googleusercontent.com',
    iosClientId: '26995370245-39crp4fgpem229373ed15vgqq9pccig8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpdqxEGG76BO_ZvamDW886TnXTzZ39Jts',
    appId: '1:26995370245:ios:362285a67b72c67f076f6c',
    messagingSenderId: '26995370245',
    projectId: 'fitness-mobile-ef3ca',
    storageBucket: 'fitness-mobile-ef3ca.firebasestorage.app',
    androidClientId: '26995370245-0hbspa2s2on5b7fur5scitq2fn0tatb8.apps.googleusercontent.com',
    iosClientId: '26995370245-39crp4fgpem229373ed15vgqq9pccig8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpH63O9ktSUDqKMvYVv_AYcrVsqs9IaB0',
    appId: '1:26995370245:web:0ab421fd4369ad60076f6c',
    messagingSenderId: '26995370245',
    projectId: 'fitness-mobile-ef3ca',
    authDomain: 'fitness-mobile-ef3ca.firebaseapp.com',
    storageBucket: 'fitness-mobile-ef3ca.firebasestorage.app',
    measurementId: 'G-4P26F2H1RB',
  );
}
